name: Release GCanvas

on:
  push:
    branches: [main]
    tags: ["v*"] # Optional: only release on version tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: GCanvas ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            dist/gcanvas.*.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
